### ISSUE TITLE
Registering new host results in error

### ISSUE THREAD

**Issue by elgervb** [tuvokki/Huna_Server#9]
Log details:

error: "E_UNKNOWN"
raw: {name: "MongoError", code: 11000,…}
code: 11000
err: "insertDocument :: caused by :: 11000 E11000 duplicate key error index: huna-dev.host.$name_1  dup key: { : "elgervanboxtel.nl" }"
name: "MongoError"
status: 500
summary: "Encountered an unexpected error"

**Comment by tuvokki** [comment]
Closed in the commit of #36
